name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build the Docker image
      uses: actions/checkout@v4
      with:
          username: ${{ secrets.DOCKER_USERNAME }} # Set this in GitHub secrets
          password: ${{ secrets.DOCKER_PASSWORD }} # Set this in GitHub secrets
     # Run make release-be
    - name: Run release build
      run: make release-be
    
